stages:
  - deploy

variables:
  TMach03: "root@10.80.3.138"
  TMach05: "root@10.80.5.138"
  TMach11: "root@10.80.11.138"

docker-deploy:
  stage: deploy
  script:
    - npm install
    - cp -rf src/assets/js/go.js node_modules/gojs/release
    - npm run build
    - ssh $TMach05 rm -rf /root/cypress-vue/
    - rsync -av -e ssh --exclude={node_modules,public,src,.git} . $TMach05:/root/cypress-vue/
    - ssh $TMach05 . /root/cypress-vue/cypress_build_images.sh
    - ssh $TMach11 rm -rf /root/cypress-vue/
    - rsync -av -e ssh --exclude={node_modules,public,src,.git} . $TMach11:/root/cypress-vue/
    - ssh $TMach11 . /root/cypress-vue/cypress_build_images.sh
  only:
    - master


tmach03-docker-deploy:
  stage: deploy
  script:
    - npm install
    - cp -rf src/assets/js/go.js node_modules/gojs/release
    - npm run build
    - rm -rf /root/cypress-vue/
    - cp ../cypress-vue /root/cypress-vue/
    - . /root/cypress-vue/cypress_build_images.sh
  only:
    - tmach03
